name: Publish Test Results
description: Publish test results and coverage reports
author: Money Keeper Team

inputs:
  backend-dir:
    description: Backend directory path
    required: false
    default: ./backend

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@9bc31d5ccc31df885eaab2b51d21c313f25284925  # v4
      with:
        path: reports/

    - uses: EnricoMi/publish-unit-test-result-action@9ab0244aac22c94290f1d57a1526375b71d45e7d  # v2
      with:
        files: reports/tests-**/TEST-*.xml
        check_name: Backend Tests
        comment_mode: always

    - uses: actions/upload-artifact@v4
      with:
        name: jacoco-report-final
        path: reports/coverage-*/
        retention-days: 30
