name: eslint-reuse

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      working-directory:
        type: string
        default: '.'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install deps (npm ci)
        working-directory: ${{ inputs.working-directory }}
        run: npm ci --ignore-scripts

      - name: Run ESLint
        working-directory: ${{ inputs.working-directory }}
        run: npm run lint
