name: eslint-reuse

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      working-directory:
        type: string
        default: '.'
      package-manager:
        type: string
        default: 'npm' # npm | pnpm | yarn
      eslint-args:
        type: string
        default: '. --max-warnings=0'
      use-reviewdog:
        type: boolean
        default: true
    secrets:
      REVIEWDOG_TOKEN:
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps (npm ci)
        run: npm ci --ignore-scripts
        working-directory: ${{ inputs.working-directory }}

      - name: Run ESLint
        run: npm run lint
        working-directory: ${{ inputs.working-directory }}
